from variants.static_graph.models.prophet import prophet_forecast
from variants.static_graph.models.arima import arima_forecast
from variants.static_graph.models.ets import ets_forecast
from variants.static_graph.models.multivariate_prophet import multivariate_prophet_forecast
from variants.static_graph.models.multivariate_var import multivariate_var_forecast
from variants.static_graph.models.multivariate_varmax import multivariate_varmax_forecast